# A list of devices you want to take the screenshots from
devices([
   "iPhone 4s",
   "iPhone 5s",
   "iPhone 6s",
   "iPhone 6s Plus"
])

languages([
  “en-US”,
  “nl-NL”

])

# The name of the scheme which contains the UI Tests
scheme “HairsprayUITests”

# Where should the resulting screenshots be stored?
#output_directory "screenshots"

clear_previous_screenshots true # remove the '#' to clear all previously generated screenshots before creating new ones

# Choose which project/workspace to use
workspace "Hairspray.xcworkspace"